# Generated by Django 5.2.4 on 2025-10-21 16:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WAV', 'WAV'), ('MP3', 'MP3'), ('FLAC', 'FLAC'), ('Stems', 'Stems'), ('AIFF', 'AIFF'), ('OGG', 'OGG'), ('M4A', 'M4A'), ('ALAC', 'ALAC')], help_text="The display name of the format, e.g. 'WAV', 'MP3', 'FLAC', 'Stems', 'AIFF'", max_length=20, unique=True)),
                ('mime_type', models.CharField(help_text="MIME type used for HTTP responses, e.g. 'audio/wav' or 'audio/mpeg'.", max_length=50)),
                ('extension', models.CharField(help_text="Typical file extension, e.g. '.wav', '.mp3', '.flac', '.stems', '.aiff', '.flac'.", max_length=10)),
                ('codec', models.CharField(blank=True, help_text="Codec or encoding standard, e.g. 'PCM 16-bit', 'MP3 (MPEG-1 Layer III)'.", max_length=50)),
                ('compression', models.CharField(choices=[('lossless', 'Lossless'), ('lossy', 'Lossy')], help_text='Indicates whether the format uses lossy or lossless compression.', max_length=20)),
                ('bit_depth', models.PositiveSmallIntegerField(blank=True, help_text='Bit depth (for uncompressed/lossless formats), e.g. 16 or 24.', null=True)),
                ('sample_rate', models.PositiveIntegerField(blank=True, help_text='Default or recommended sample rate in Hz (e.g. 44100, 48000).', null=True)),
                ('file_size_factor', models.DecimalField(decimal_places=2, default=1.0, help_text='Relative size factor vs WAV (e.g. MP3 = 0.15 means 15% of WAV size).', max_digits=5)),
                ('active', models.BooleanField(default=True, help_text='Whether this format is currently supported.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'File Format',
                'verbose_name_plural': 'File Formats',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the song.', primary_key=True, serialize=False)),
                ('artists_features_line', models.CharField(blank=True, default='GardlyRadicle', help_text='The artists of the song formatted for posting.', max_length=255, null=True)),
                ('isrc_code', models.CharField(blank=True, help_text='The ISRC code of the song.', max_length=13, null=True)),
                ('upc_code', models.CharField(blank=True, help_text='The UPC code of the song.', max_length=12, null=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='The thumbnail image of the song.', null=True, upload_to='thumbnails/')),
                ('vinyl_thumbnail', models.ImageField(blank=True, help_text='The vinyl thumbnail image of the song.', null=True, upload_to='vinyl_thumbnails/')),
                ('cover_art', models.ImageField(blank=True, help_text='The cover art image of the song.', null=True, upload_to='cover_arts/')),
                ('title', models.CharField(help_text='The primary title of the song.', max_length=255)),
                ('alternate_titles', models.JSONField(blank=True, default=list, help_text='Array of alternative titles, common misspellings, or working titles.', null=True)),
                ('version_subtitle', models.CharField(blank=True, help_text="e.g., 'Instrumental,' 'Acoustic Mix,' 'Radio Edit,' 'Remix feat. [Artist]'.", max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='A brief overview or detailed description of the song.', null=True)),
                ('release_date', models.DateField(default=django.utils.timezone.now, help_text='The date the song was first commercially released.')),
                ('language', models.CharField(default='en', help_text="The primary language of the lyrics (if any), e.g., 'en', 'es'.", max_length=10)),
                ('explicit_content', models.BooleanField(default=False, help_text='Flag indicating if the song contains explicit lyrics or themes.')),
                ('lyrics', models.TextField(blank=True, help_text='The lyrics of the song.', null=True)),
                ('bpm', models.IntegerField(blank=True, default=120, help_text='Beats Per Minute (BPM) of the song.', null=True)),
                ('key', models.CharField(blank=True, default='C Major', help_text="Musical key of the song (e.g., 'C Major', 'A Minor', 'F#m').", max_length=50, null=True)),
                ('time_signature', models.CharField(blank=True, default='4/4', help_text="Time signature of the song (e.g., '4/4', '3/4').", max_length=10, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, default=120, help_text='Total duration of the song in seconds.', null=True)),
                ('genres', models.JSONField(blank=True, default=list, help_text="Array of primary and secondary genres (e.g., ['Hip-Hop', 'Trap']).", null=True)),
                ('moods', models.JSONField(blank=True, default=list, help_text="Array of moods or emotions evoked (e.g., ['Uplifting', 'Melancholy']).", null=True)),
                ('keywords_tags', models.JSONField(blank=True, default=list, help_text="Additional keywords for search and categorization (e.g., ['summer', 'driving']).", null=True)),
                ('instruments', models.JSONField(blank=True, default=list, help_text="List of prominent instruments in the track (e.g., ['piano', 'drums']).", null=True)),
                ('vocal_description', models.CharField(blank=True, help_text="Describes the vocal presence (e.g., 'Male Lead', 'No Vocals').", max_length=100, null=True)),
                ('buy_link', models.URLField(blank=True, help_text='Link to purchase the track.', null=True)),
                ('stream_link', models.URLField(blank=True, help_text='Link to stream the track.', null=True)),
                ('download_link', models.URLField(blank=True, help_text='Link to download the track.', null=True)),
                ('donation_link', models.URLField(blank=True, help_text='Link to donate to the creator. For example, donate to support making full song with the beat.', null=True)),
                ('note', models.TextField(blank=True, help_text='Additional notes or comments about the track.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicProfessional',
            fields=[
                ('professional_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ref_code', models.CharField(blank=True, help_text='ISNI or other reference code-if an artist', max_length=13, null=True)),
                ('pro_affiliation', models.CharField(blank=True, help_text="The professional affiliation of the artist (e.g., 'ASCAP', 'BMI', 'SoundExchange').", max_length=100, null=True)),
                ('ipi_number', models.CharField(blank=True, help_text='The IPI number of the artist.', max_length=20, null=True)),
                ('note', models.TextField(blank=True, help_text='Additional notes or comments.', null=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music_professional', to='common.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('contributor_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the contributor.', primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Composer', 'Composer'), ('Lyricist', 'Lyricist'), ('Producer', 'Producer'), ('Songwriter', 'Songwriter'), ('Engineer', 'Engineer'), ('Singer', 'Singer'), ('Performer', 'Performer'), ('Various', 'Various'), ('Other', 'Other')], help_text="The role of the contributor (e.g., 'Composer', 'Lyricist', 'Producer', Songwriter, Engineer, Singer, Performer ).", max_length=255)),
                ('note', models.TextField(blank=True, help_text='Additional notes or comments about the contributor.', null=True)),
                ('music_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to='music.musicprofessional')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the publisher.', primary_key=True, serialize=False)),
                ('website', models.URLField(blank=True, help_text='Official website of the publisher.', null=True)),
                ('pro_affiliation', models.CharField(blank=True, help_text="The publisher's PRO (e.g., 'ASCAP', 'BMI').", max_length=100, null=True)),
                ('note', models.TextField(blank=True, help_text='Additional notes or comments about the publisher.', null=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='common.contact')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('social_media_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('platform', models.CharField(max_length=50)),
                ('music_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='music.musicprofessional')),
            ],
        ),
        migrations.CreateModel(
            name='Publishing',
            fields=[
                ('publishing_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the publishing.', primary_key=True, serialize=False)),
                ('publishing_date', models.DateField(blank=True, help_text='The date the publishing was published.', null=True)),
                ('note', models.TextField(blank=True, help_text='Additional notes or comments about the publishing.', null=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishings', to='music.publisher')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishings', to='music.track')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('library_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the library.', primary_key=True, serialize=False)),
                ('library_name', models.CharField(default='Library', help_text='The name of the library.', max_length=255)),
                ('note', models.TextField(blank=True, help_text='Additional notes or comments about the library.', null=True)),
                ('library_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL)),
                ('track', models.ManyToManyField(related_name='libraries', to='music.track')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('contribution_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the contribution.', primary_key=True, serialize=False)),
                ('contribution_type', models.CharField(help_text="The type of contribution (e.g., 'composer', 'performer', 'engineer').", max_length=255)),
                ('contribution_description', models.TextField(blank=True, help_text='Getting more specific about the contribution/input.', null=True)),
                ('contribution_date', models.DateField(blank=True, help_text='The date the contribution was made.', null=True)),
                ('contribution_note', models.TextField(blank=True, help_text='Additional notes or comments about the contribution.', null=True)),
                ('contributor', models.ForeignKey(help_text='The contributor who made the contribution.', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='music.contributor')),
                ('track', models.ForeignKey(help_text='The track that was contributed to.', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='music.track')),
            ],
        ),
        migrations.CreateModel(
            name='TrackStorageFile',
            fields=[
                ('track_storage_file_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the track storage file.', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, help_text='Description of the track storage file.', max_length=255, null=True)),
                ('file_path', models.FileField(help_text='The track storage file.', upload_to='track_storage_files')),
                ('bit_rate', models.IntegerField(blank=True, help_text='The bit rate of the audio file of the song (in kbps).', null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='The file size of the audio file of the song (in bytes).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date the file was created/uploaded.')),
                ('file_format', models.ForeignKey(help_text='The file format of the audio file from the file_format model.', on_delete=django.db.models.deletion.PROTECT, related_name='track_storage_files', to='music.fileformat')),
            ],
        ),
    ]
