# Generated by Django 5.2.4 on 2025-10-21 16:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_fileformat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicprofessional',
            name='professional_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the music professional.', primary_key=True, serialize=False),
        ),
    ]
