# Generated by Django 5.2.4 on 2025-10-21 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('music', '0003_alter_musicprofessional_professional_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicprofessional',
            name='contact',
            field=models.OneToOneField(help_text='The contact information for the music professional.', on_delete=django.db.models.deletion.CASCADE, related_name='music_professional', to='common.contact'),
        ),
    ]
