# Generated by Django 5.2.4 on 2025-10-21 17:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_musicprofessional_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='social_media_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the social media link.', primary_key=True, serialize=False),
        ),
    ]
