# Generated by Django 5.2.4 on 2025-10-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_socialmedialink_social_media_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('Creative', 'Creative'), ('Technical', 'Technical'), ('Administrative', 'Administrative'), ('Various', 'Various')], help_text="The type of contribution (e.g., 'composer', 'performer', 'engineer').", max_length=255),
        ),
    ]
