# Generated by Django 5.2.4 on 2025-10-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_contribution_contribution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileformat',
            name='name',
            field=models.CharField(choices=[('WAV', 'WAV'), ('MP3', 'MP3'), ('FLAC', 'FLAC'), ('Stems', 'Stems'), ('AIFF', 'AIFF'), ('OGG', 'OGG'), ('M4A', 'M4A'), ('ALAC', 'ALAC'), ('Sample', 'Sample')], help_text="The display name of the format, e.g. 'WAV', 'MP3', 'FLAC', 'Stems', 'AIFF'", max_length=20),
        ),
    ]
