# Generated by Django 5.2.4 on 2025-10-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_fileformat_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='track',
            new_name='tracks',
        ),
    ]
