# Generated by Django 5.2.4 on 2025-12-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_rename_track_library_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
