# Generated by Django 5.2.4 on 2026-01-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_socialmedialink_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('Composer', 'Composer'), ('Lyricist', 'Lyricist'), ('Producer', 'Producer'), ('Songwriter', 'Songwriter'), ('Engineer', 'Engineer'), ('Singer', 'Singer'), ('Performer', 'Performer'), ('Various', 'Various'), ('Other', 'Other')], default='Various', help_text="The role of the contributor (e.g., 'Composer', 'Lyricist', 'Producer', Songwriter, Engineer, Singer, Performer ).", max_length=255),
        ),
    ]
