# Generated by Django 5.2.4 on 2026-01-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_alter_contributor_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileformat',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='trackstoragefile',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
