# Generated by Django 5.2.4 on 2025-10-19 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company')], default='INDIVIDUAL', max_length=10)),
                ('first_name', models.CharField(blank=True, help_text='The first name of the contact.', max_length=255)),
                ('last_name', models.CharField(blank=True, help_text='The last name of the contact.', max_length=255)),
                ('sudo_name', models.CharField(blank=True, help_text='The artist name, alias, or stage name of the contact.', max_length=255)),
                ('company_name', models.CharField(blank=True, help_text='The name of the company or organization.', max_length=255)),
                ('registration_number', models.CharField(blank=True, help_text='The registration number of the company or organization.', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('BILLING', 'Billing'), ('SHIPPING', 'Shipping'), ('MAILING', 'Mailing')], default='MAILING', max_length=10)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(help_text='State or Province', max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='common.contact')),
            ],
        ),
    ]
