# Generated by Django 5.2.4 on 2025-11-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('BILLING', 'Billing'), ('SHIPPING', 'Shipping'), ('MAILING', 'Mailing'), ('REGISTRATION', 'Registration')], default='MAILING', max_length=15),
        ),
    ]
