# Generated by Django 5.2.4 on 2026-01-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company_name',
            field=models.CharField(blank=True, help_text='The name of the company or organization.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='registration_number',
            field=models.CharField(blank=True, help_text='The registration number of the company or organization.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sudo_name',
            field=models.CharField(blank=True, help_text='The artist name, alias, or stage name of the contact.', max_length=255, null=True),
        ),
    ]
