# Generated by Django 5.2.4 on 2025-12-31 04:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newslettercampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('newsletter_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Content of the newsletter. Supports rich text.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('target_category', models.ForeignKey(blank=True, help_text='Optional: Send only to subscribers of this category. Leave blank to send to all active subscribers.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletter.newslettercategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='NewsletterCampaign',
        ),
    ]
