# Generated by Django 5.2.4 on 2026-01-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_subscription_unsubscribed_at_newsletter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='newslettercategory',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
