# Generated by Django 5.2.4 on 2025-12-18 20:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='usd', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.50'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='currency',
            field=models.CharField(default='usd', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='usd', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], max_length=10),
        ),
    ]
