# Generated by Django 5.2.4 on 2026-01-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
