# Generated by Django 5.2.4 on 2025-10-21 16:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('copyright_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the copyright.', primary_key=True, serialize=False)),
                ('copyright_type', models.CharField(choices=[('Recording Copyright', 'Recording Copyright'), ('Composition Copyright', 'Composition Copyright')], help_text="The type of copyright (e.g., 'Recording Copyright', 'Composition Copyright').", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Additional notes or comments about the copyright.', null=True)),
                ('copyright_date', models.DateField(blank=True, help_text='The date the copyright for the sound recording was established.', null=True)),
                ('note', models.TextField(blank=True, help_text='Additional notes or comments about the copyright.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CopyrightHolding',
            fields=[
                ('copyright_holding_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the copyright holder.', primary_key=True, serialize=False)),
                ('copyright_holder_split', models.IntegerField(help_text="The percentage of the copyright holder's share of the copyright.")),
                ('copyright_holding_note', models.TextField(blank=True, help_text='Additional notes or comments about the copyright holder.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CopyrightStatus',
            fields=[
                ('copyright_status_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the copyright status.', primary_key=True, serialize=False)),
                ('copyright_status_option', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')], help_text="The type of copyright status (e.g., 'Active', 'Expired', 'Cancelled').", max_length=255)),
                ('copyright_status_date', models.DateField(blank=True, help_text='The date the copyright status was created.', null=True)),
                ('copyright_status_note', models.TextField(blank=True, help_text='Additional notes or comments about the copyright status.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the license.', primary_key=True, serialize=False)),
                ('license_agreement_file', models.FileField(help_text='The license agreement for the sound recording.', upload_to='license_agreements')),
                ('created_date', models.DateField(auto_now_add=True, help_text='The date the license for the sound recording was established.')),
                ('expiration_date', models.DateField(blank=True, help_text='The expiration date of the license for the sound recording.', null=True)),
                ('license_note', models.TextField(blank=True, help_text='Additional notes or comments about the license.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='License_type',
            fields=[
                ('license_type_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Unique identifier for the license type (e.g., 'Standard Sync License- mp3 and wav').", primary_key=True, serialize=False)),
                ('license_type_name', models.CharField(help_text='The name of the license type.', max_length=255)),
                ('license_template', models.TextField(default=None, help_text='The license template for the license type.')),
                ('license_term', models.CharField(help_text="Amount of years the license is valid for (e.g., '1 Year', '2 Years', unlimited').", max_length=255)),
                ('transferability', models.CharField(choices=[('Transferable', 'Transferable'), ('Non-Transferable', 'Non-Transferable')], help_text="The transferability of the license option (e.g., 'Transferable', 'Non-Transferable').", max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='The price for the license option.', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text="The currency for the license option (e.g., 'USD', 'EUR', 'GBP').", max_length=255)),
                ('download_limit', models.CharField(help_text="The download limit for the license option (e.g., 'Unlimited', '100').", max_length=255)),
                ('streaming_limit', models.CharField(help_text="The streaming limit for the license option (e.g., 'Unlimited', '100').", max_length=255)),
                ('monetized_radio_plays', models.CharField(help_text="The monetized radio plays for the license option (e.g., 'Unlimited', '100').", max_length=255)),
                ('video_rights', models.CharField(help_text='The video rights for the license option.', max_length=255)),
                ('royalty_payment', models.CharField(help_text='The royalty payment for the license option.', max_length=255)),
                ('credit_requirement', models.CharField(default='Yes', help_text='The credit requirement for the license option.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Licensee',
            fields=[
                ('licensee_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the licensee.', primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, choices=[('Composer', 'Composer'), ('Lyricist', 'Lyricist'), ('Producer', 'Producer'), ('Songwriter', 'Songwriter'), ('Engineer', 'Engineer'), ('Singer', 'Singer'), ('Performer', 'Performer'), ('Various', 'Various'), ('Other', 'Other')], help_text="The role of the licensee (e.g., 'Composer', 'Lyricist', 'Producer', Songwriter, Engineer, Singer, Performer ).", max_length=255, null=True)),
                ('note', models.TextField(blank=True, help_text='Additional notes or comments about the licensee.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseHolding',
            fields=[
                ('license_holding_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the license holding.', primary_key=True, serialize=False)),
                ('licensee_split', models.IntegerField(blank=True, help_text="The percentage of the licensee's share of the license.", null=True)),
                ('license_holding_note', models.TextField(blank=True, help_text='Additional notes or comments about the license holding.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseStatus',
            fields=[
                ('license_status_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the license status.', primary_key=True, serialize=False)),
                ('license_status_option', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')], help_text="The type of license status (e.g., 'Active', 'Expired', 'Cancelled').", max_length=255)),
                ('license_status_date', models.DateField(help_text='The date the license status was created.')),
                ('license_status_note', models.TextField(blank=True, help_text='Additional notes or comments about the license status.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackLicenseOptions',
            fields=[
                ('track_license_option_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the track license option.', primary_key=True, serialize=False)),
            ],
        ),
    ]
