# Generated by Django 5.2.4 on 2025-10-21 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licenses', '0001_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyright',
            name='track',
            field=models.ForeignKey(help_text='The track to which the copyright applies.', on_delete=django.db.models.deletion.CASCADE, related_name='copyrights', to='music.track'),
        ),
        migrations.AddField(
            model_name='copyrightholding',
            name='copyright',
            field=models.ForeignKey(help_text='The copyright record.', on_delete=django.db.models.deletion.CASCADE, related_name='copyright_holdings', to='licenses.copyright'),
        ),
        migrations.AddField(
            model_name='copyrightholding',
            name='copyright_holder',
            field=models.ForeignKey(help_text='The copyright holder.', on_delete=django.db.models.deletion.CASCADE, related_name='copyright_holdings', to='music.musicprofessional'),
        ),
        migrations.AddField(
            model_name='copyrightstatus',
            name='copyright',
            field=models.ForeignKey(help_text='The copyright record.', on_delete=django.db.models.deletion.CASCADE, related_name='copyright_status', to='licenses.copyright'),
        ),
        migrations.AddField(
            model_name='licensee',
            name='music_professional',
            field=models.ForeignKey(blank=True, help_text='The licensee.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licensees', to='music.musicprofessional'),
        ),
        migrations.AddField(
            model_name='licenseholding',
            name='license',
            field=models.ForeignKey(help_text='The license record.', on_delete=django.db.models.deletion.CASCADE, related_name='license_holdings', to='licenses.license'),
        ),
        migrations.AddField(
            model_name='licenseholding',
            name='licensee',
            field=models.ForeignKey(help_text='The licensee.', on_delete=django.db.models.deletion.CASCADE, related_name='license_holdings', to='licenses.licensee'),
        ),
        migrations.AddField(
            model_name='licensestatus',
            name='license',
            field=models.ForeignKey(help_text='The license record.', on_delete=django.db.models.deletion.CASCADE, related_name='license_status', to='licenses.license'),
        ),
        migrations.AddField(
            model_name='tracklicenseoptions',
            name='license_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_license_options', to='licenses.license_type'),
        ),
        migrations.AddField(
            model_name='tracklicenseoptions',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_license_options', to='music.track'),
        ),
        migrations.AddField(
            model_name='tracklicenseoptions',
            name='track_storage_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_license_options', to='music.trackstoragefile'),
        ),
        migrations.AddField(
            model_name='license',
            name='track_license_option',
            field=models.ForeignKey(help_text="The type of license (e.g., 'Wav, mp3, stems').", on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='licenses.tracklicenseoptions'),
        ),
    ]
