# Generated by Django 5.2.4 on 2025-11-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_agreement_file',
            field=models.FileField(blank=True, help_text='The license agreement for the sound recording.', null=True, upload_to='license_agreements'),
        ),
    ]
