# Generated by Django 5.2.4 on 2025-12-18 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_alter_license_license_agreement_file'),
        ('transactions', '0002_alter_order_currency_alter_order_tax_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='ordered_item',
            field=models.ForeignKey(blank=True, help_text='The order item for the license.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='transactions.orderitem'),
        ),
    ]
