# Generated by Django 5.2.4 on 2025-12-19 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_license_ordered_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='ordered_item',
            new_name='order_item',
        ),
    ]
