# Generated by Django 5.2.4 on 2025-12-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0005_rename_ordered_item_license_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='license_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='The date and time the license email was sent.', null=True),
        ),
    ]
