# Generated by Django 5.2.4 on 2025-12-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0006_license_license_email_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date the license for the sound recording was established.'),
        ),
        migrations.AlterField(
            model_name='license',
            name='expiration_date',
            field=models.DateTimeField(blank=True, help_text='The expiration date of the license for the sound recording.', null=True),
        ),
        migrations.AlterField(
            model_name='licensestatus',
            name='license_status_date',
            field=models.DateTimeField(help_text='The date the license status was created.'),
        ),
    ]
