# Generated by Django 5.2.4 on 2026-01-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0007_alter_license_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyrightholding',
            name='copyright_holder_split',
            field=models.IntegerField(default=100, help_text="The percentage of the copyright holder's share of the copyright."),
        ),
        migrations.AlterField(
            model_name='licensee',
            name='role',
            field=models.CharField(blank=True, choices=[('Composer', 'Composer'), ('Lyricist', 'Lyricist'), ('Producer', 'Producer'), ('Songwriter', 'Songwriter'), ('Engineer', 'Engineer'), ('Singer', 'Singer'), ('Performer', 'Performer'), ('Various', 'Various'), ('Other', 'Other')], default='Various', help_text="The role of the licensee (e.g., 'Composer', 'Lyricist', 'Producer', Songwriter, Engineer, Singer, Performer ).", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='licensestatus',
            name='license_status_date',
            field=models.DateTimeField(auto_now=True, help_text='The date the license status was created.'),
        ),
        migrations.AlterField(
            model_name='licensestatus',
            name='license_status_option',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], help_text="The type of license status (e.g., 'Active', 'Expired', 'Cancelled').", max_length=255),
        ),
    ]
