# Generated by Django 5.2.4 on 2026-01-17 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0008_alter_copyrightholding_copyright_holder_split_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='license_zips/')),
                ('license', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license_downloads', to='licenses.license')),
            ],
        ),
    ]
